---
- hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - git
          - tmux
          - nano
          - openvpn
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Copy OpenVPN configuration file
      copy:
        src: ./lab.ovpn
        dest: /etc/openvpn/client.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start OpenVPN service
      systemd:
        name: openvpn@client
        enabled: yes
        state: started