---
- hosts: all
  become: yes
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
      become: yes

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - gpg
          - python3
          - python3-pip
          - openssl
          - git
          - tmux
        state: latest
        update_cache: true
      register: output
      become: yes

    - name: Show results
      ansible.builtin.debug:
        var: output
      become: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      become: yes

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bookworm stable
        state: present
      become: yes
    
    - name: Install docker and docker compose
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
          - docker-buildx-plugin
          - containerd.io
        state: latest
        update_cache: true
      register: output
      become: yes

    - name: Show results
      ansible.builtin.debug:
        var: output
      become: yes

    - name: Copy OpenVPN configuration file
      copy:
        src: ./lab.ovpn
        dest: /etc/openvpn/client.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy Hack The Box Creds
      copy:
        src: ./.cred
        dest: /home/vagrant/cred
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start OpenVPN service
      systemd:
        name: openvpn@client
        enabled: yes
        state: started